# theme: minima      # remove or comment this out
remote_theme: ngzhio/jekyll-theme-hamilton
skin: sunrise        # this is where “sunrise” belongs

author: Sarah Saneei
avatar: /assets/photos/pic.png

collections:
  poster:
    output: true
    permalink: /poster/:path/

excerpt_separator: "<!--more-->"
